export const BoxTailStyles = {
	"#BoxTail-top-right": {
		content: '',
		position: "absolute",
		border: "10px solid transparent",
		borderBottom: 0,
		borderTop: "11px solid #fff",
		bottom: "-10px",
		left: "7px",
	},
	"#BoxTail-top-right-border": {
		content: '',
		position: "absolute",
		border: "10px solid transparent",
		borderBottom: 0,
		borderTop: "11px solid black",
		bottom: "-12px",
		left: "7px",
	},
	"#BoxTail-top-left": {
		content: '',
		position: "absolute",
		border: "10px solid transparent",
		borderBottom: 0,
		borderTop: "11px solid #fff",
		bottom: "-10px",
		left: "85%",
	},
	"#BoxTail-top-left-border": {
		content: '',
		position: "absolute",
		border: "10px solid transparent",
		borderBottom: 0,
		borderTop: "11px solid black",
		bottom: "-12px",
		left: "85%",
	},
	"#BoxTail-bottom-left": {
		content: '',
		position: "absolute",
		border: "10px solid transparent",
		borderTop: 0,
		borderBottom: "11px solid #fff",
		top: "-10px",
		left: "85%",
	},
	"#BoxTail-bottom-left-border": {
		content: '',
		position: "absolute",
		border: "10px solid transparent",
		borderTop: 0,
		borderBottom: "11px solid black",
		top: "-12px",
		left: "85%",
	},
	"#BoxTail-bottom-right": {
		content: '',
		position: "absolute",
		border: "10px solid transparent",
		borderTop: 0,
		borderBottom: "11px solid #fff",
		top: "-10px",
		left: "5%",
	},
	"#BoxTail-bottom-right-border": {
		content: '',
		position: "absolute",
		border: "10px solid transparent",
		borderTop: 0,
		borderBottom: "11px solid black",
		top: "-12px",
		left: "5%",
	},
}